"use client";

import { BarChart3, TrendingUp, AlertTriangle } from "lucide-react";

interface GenerativeCardProps {
    type: "chart" | "risk" | "table";
}

export function GenerativeCard({ type }: GenerativeCardProps) {
    if (type === "chart") {
        return (
            <div className="w-full bg-card border border-border rounded-lg p-4 shadow-xl animate-slide-up">
                <div className="flex items-center justify-between mb-4 border-b border-border pb-2">
                    <div className="flex items-center gap-2">
                        <TrendingUp className="h-5 w-5 text-primary" />
                        <h3 className="font-semibold text-foreground">Performance (7D)</h3>
                    </div>
                    <span className="text-xs text-muted-foreground">Generated by Tambo AI</span>
                </div>
                <div className="h-40 flex items-end justify-between gap-1 px-2">
                    {[40, 65, 45, 80, 55, 90, 75].map((h, i) => (
                        <div
                            key={i}
                            style={{ height: `${h}%` }}
                            className="flex-1 bg-primary/20 hover:bg-primary/40 transition-colors rounded-t-sm relative group"
                        >
                            <div
                                style={{ height: `${h}%` }}
                                className="absolute bottom-0 w-full bg-primary/80 group-hover:bg-primary transition-colors opacity-80"
                            />
                        </div>
                    ))}
                </div>
                <div className="flex justify-between mt-2 text-xs text-muted-foreground">
                    <span>Mon</span>
                    <span>Sun</span>
                </div>
            </div>
        );
    }

    if (type === "risk") {
        return (
            <div className="w-full bg-card border border-border rounded-lg p-4 shadow-xl animate-slide-up">
                <div className="flex items-center justify-between mb-4 border-b border-border pb-2">
                    <div className="flex items-center gap-2">
                        <AlertTriangle className="h-5 w-5 text-orange-500" />
                        <h3 className="font-semibold text-foreground">Risk Analysis</h3>
                    </div>
                    <span className="text-xs text-muted-foreground">Generated by Tambo AI</span>
                </div>
                <div className="flex flex-col gap-4">
                    <div className="space-y-1">
                        <div className="flex justify-between text-sm">
                            <span>Portfolio Volatility</span>
                            <span className="text-orange-400 font-mono">High (85/100)</span>
                        </div>
                        <div className="h-2 w-full bg-secondary/20 rounded-full overflow-hidden">
                            <div className="h-full w-[85%] bg-linear-to-r from-yellow-500 to-red-500" />
                        </div>
                    </div>
                    <p className="text-sm text-muted-foreground">
                        Concentration warning: 80% of assets in memes.
                    </p>
                </div>
            </div>
        )
    }

    return null;
}
